"""Gold star-schema manifests: loading, validation, and placeholder resolution.

Gold models conformed Silver entities into Kimball star-schema tables
(dim_*, fact_*, plus a generated date dimension) per ADR-005. A gold table
spec declares its Silver source, kind, primary key, foreign-key references,
and (for facts) date keys and aggregations. As with Bronze/Silver, templates
carry ``{placeholder}`` tokens resolved from environment variables.

Validation is pure Python and, when supplied an ``entity_schema`` (the
generator pack's columns), pins every referenced column to a real field. The
date dimension is generated by :func:`date_dimension_rows`, which is pure
Python and fully unit-testable.
"""

from __future__ import annotations

import copy
import re
from collections.abc import Mapping
from datetime import date, timedelta
from typing import Any

from .bronze_manifest import ManifestError, load_manifest, resolve_path

SUPPORTED_KINDS = frozenset({"dimension", "date_dimension", "fact"})
SUPPORTED_AGGREGATIONS = frozenset({"sum", "avg", "min", "max", "count", "count_true"})
DEFAULT_SCHEMA = "gold"
DERIVED_COLUMN = "date_key"

_TABLE_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_AGGREGATION_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_PLACEHOLDER_RE = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")
_KNOWN_PLACEHOLDERS = frozenset({"catalog", "landing", "schema", "table"})


def load_gold_manifest(path: str | Any) -> dict[str, Any]:
    """Load a Gold manifest JSON file into a dict."""
    return load_manifest(path)


def validate_gold_manifest(
    manifest: Mapping[str, Any], entity_schema: Mapping[str, Mapping[str, Any]] | None = None
) -> None:
    """Validate the structure of a Gold manifest, raising on any defect."""
    _require(manifest, "manifest must be an object")
    metadata = _require(manifest.get("metadata"), "metadata is required")
    pipeline = _require(metadata.get("pipeline"), "metadata.pipeline is required")
    if not isinstance(pipeline, str) or not pipeline.strip():
        raise ManifestError("metadata.pipeline must be a non-empty string")

    schema = manifest.get("schema", DEFAULT_SCHEMA)
    if not isinstance(schema, str) or not schema.strip():
        raise ManifestError("schema must be a non-empty string")
    _check_tokens(schema, context="schema")

    tables = _require(manifest.get("tables"), "tables is required")
    if not isinstance(tables, list) or not tables:
        raise ManifestError("tables must be a non-empty list")

    gold_names: set[str] = set()
    for index, table in enumerate(tables):
        _validate_table_identity(table, index, gold_names)
    for index, table in enumerate(tables):
        _validate_table_body(table, index, gold_names, entity_schema)

    if "target" in manifest:
        target = manifest["target"]
        if not isinstance(target, str) or not target.strip():
            raise ManifestError("target must be a non-empty string")
        _check_tokens(target, context="target")


def _validate_table_identity(table: Any, index: int, gold_names: set[str]) -> None:
    if not isinstance(table, Mapping):
        raise ManifestError(f"tables[{index}] must be an object")
    name = _require(table.get("name"), f"tables[{index}].name is required")
    if not isinstance(name, str) or not _TABLE_NAME_RE.match(name):
        raise ManifestError(
            f"tables[{index}].name '{name}' is not a valid table name "
            "(alphanumeric/underscore, starting with a letter or underscore)"
        )
    if name in gold_names:
        raise ManifestError(f"duplicate table name: {name}")
    gold_names.add(name)


def _validate_table_body(
    table: Mapping[str, Any],
    index: int,
    gold_names: set[str],
    entity_schema: Mapping[str, Mapping[str, Any]] | None,
) -> None:
    name = table["name"]
    kind = _require(table.get("kind"), f"tables[{index}].kind is required")
    if kind not in SUPPORTED_KINDS:
        raise ManifestError(
            f"tables[{index}].kind '{kind}' is not supported "
            f"(expected one of {sorted(SUPPORTED_KINDS)})"
        )

    primary_key = _require(table.get("primary_key"), f"tables[{index}].primary_key is required")
    primary_key_columns = primary_key if isinstance(primary_key, list) else [primary_key]
    if not primary_key_columns or not all(
        isinstance(col, str) and _TABLE_NAME_RE.match(col) for col in primary_key_columns
    ):
        raise ManifestError(
            f"tables[{index}].primary_key must be a column name or list of column names"
        )

    expectations = _validate_expectations(table.get("expectations", []), index)

    if kind == "date_dimension":
        date_range = _require(table.get("date_range"), f"tables[{index}].date_range is required")
        _validate_date_range(date_range, index)
        return

    source = _require(table.get("source"), f"tables[{index}].source is required")
    if not isinstance(source, Mapping):
        raise ManifestError(f"tables[{index}].source must be an object")
    source_table = _require(source.get("table"), f"tables[{index}].source.table is required")
    if not isinstance(source_table, str) or not source_table.strip():
        raise ManifestError(f"tables[{index}].source.table must be a non-empty string")
    _check_tokens(source_table, context=f"tables[{index}].source.table")

    entity_columns = _source_entity_columns(source_table, entity_schema)

    for column in primary_key_columns:
        if entity_columns is not None and column not in entity_columns and column != DERIVED_COLUMN:
            raise ManifestError(
                f"tables[{index}].primary_key column '{column}' is not a column of '{name}'"
            )

    foreign_keys = table.get("foreign_keys", [])
    if not isinstance(foreign_keys, list):
        raise ManifestError(f"tables[{index}].foreign_keys must be a list")
    for fk_index, fk in enumerate(foreign_keys):
        _validate_foreign_key(fk, fk_index, index, name, gold_names, entity_columns)

    if kind == "fact":
        date_key = table.get("date_key")
        if date_key is not None:
            if not isinstance(date_key, Mapping) or not isinstance(date_key.get("column"), str):
                raise ManifestError(f"tables[{index}].date_key must be an object with a 'column'")
            if entity_columns is not None and date_key["column"] not in entity_columns:
                raise ManifestError(
                    f"tables[{index}].date_key column '{date_key['column']}' is not a column of "
                    f"'{name}'"
                )
        aggregate = table.get("aggregate")
        if aggregate is not None:
            _validate_aggregate(aggregate, index, name, entity_columns)

    if expectations and kind == "fact":
        for expectation in expectations:
            constraint = expectation["constraint"]
            if (
                entity_columns is not None
                and DERIVED_COLUMN in constraint
                and not (table.get("date_key") or (table.get("aggregate") or {}).get("date_key"))
            ):
                raise ManifestError(
                    f"tables[{index}] references {DERIVED_COLUMN} in expectations but declares "
                    "no date_key"
                )


def _validate_expectations(expectations: Any, index: int) -> list[dict[str, str]]:
    if not isinstance(expectations, list):
        raise ManifestError(f"tables[{index}].expectations must be a list")
    result: list[dict[str, str]] = []
    names: set[str] = set()
    for expectation_index, expectation in enumerate(expectations):
        if not isinstance(expectation, Mapping):
            raise ManifestError(
                f"tables[{index}].expectations[{expectation_index}] must be an object"
            )
        exp_name = expectation.get("name")
        constraint = expectation.get("constraint")
        if not isinstance(exp_name, str) or not exp_name.strip():
            raise ManifestError(
                f"tables[{index}].expectations[{expectation_index}].name must be a non-empty string"
            )
        if not isinstance(constraint, str) or not constraint.strip():
            raise ManifestError(
                f"tables[{index}].expectations[{expectation_index}].constraint must be a "
                "non-empty string"
            )
        if exp_name in names:
            raise ManifestError(f"tables[{index}].expectations has duplicate name '{exp_name}'")
        names.add(exp_name)
        result.append({"name": exp_name, "constraint": constraint})
    return result


def _validate_foreign_key(
    fk: Any,
    fk_index: int,
    table_index: int,
    table_name: str,
    gold_names: set[str],
    entity_columns: Mapping[str, Any] | None,
) -> None:
    if not isinstance(fk, Mapping):
        raise ManifestError(f"tables[{table_index}].foreign_keys[{fk_index}] must be an object")
    column = fk.get("column")
    references = fk.get("references")
    if not isinstance(column, str) or not column.strip():
        raise ManifestError(
            f"tables[{table_index}].foreign_keys[{fk_index}].column must be a non-empty string"
        )
    if not isinstance(references, str) or not references.strip():
        raise ManifestError(
            f"tables[{table_index}].foreign_keys[{fk_index}].references must be a non-empty string"
        )
    if references not in gold_names:
        raise ManifestError(
            f"tables[{table_index}].foreign_keys[{fk_index}] references unknown gold table "
            f"'{references}'"
        )
    if entity_columns is not None and column not in entity_columns:
        raise ManifestError(
            f"tables[{table_index}].foreign_keys[{fk_index}] column '{column}' is not a column "
            f"of '{table_name}'"
        )


def _validate_aggregate(
    aggregate: Any, index: int, table_name: str, entity_columns: Mapping[str, Any] | None
) -> None:
    if not isinstance(aggregate, Mapping):
        raise ManifestError(f"tables[{index}].aggregate must be an object")
    group_by = aggregate.get("group_by")
    if (
        not isinstance(group_by, list)
        or not group_by
        or not all(isinstance(col, str) and col for col in group_by)
    ):
        raise ManifestError(
            f"tables[{index}].aggregate.group_by must be a non-empty list of columns"
        )
    for column in group_by:
        if entity_columns is not None and column not in entity_columns:
            raise ManifestError(
                f"tables[{index}].aggregate.group_by column '{column}' is not a column of "
                f"'{table_name}'"
            )
    date_key = aggregate.get("date_key")
    if not isinstance(date_key, Mapping) or not isinstance(date_key.get("column"), str):
        raise ManifestError(f"tables[{index}].aggregate.date_key must be an object with a 'column'")
    if entity_columns is not None and date_key["column"] not in entity_columns:
        raise ManifestError(
            f"tables[{index}].aggregate.date_key column '{date_key['column']}' is not a column "
            f"of '{table_name}'"
        )
    measures = aggregate.get("measures")
    if not isinstance(measures, list) or not measures:
        raise ManifestError(f"tables[{index}].aggregate.measures must be a non-empty list")
    aliases: set[str] = set()
    for measure_index, measure in enumerate(measures):
        if not isinstance(measure, Mapping):
            raise ManifestError(
                f"tables[{index}].aggregate.measures[{measure_index}] must be an object"
            )
        column = measure.get("column")
        agg = measure.get("agg")
        alias = measure.get("as")
        if not isinstance(column, str) or not column:
            raise ManifestError(
                f"tables[{index}].aggregate.measures[{measure_index}].column must be a "
                "non-empty string"
            )
        if agg not in SUPPORTED_AGGREGATIONS:
            raise ManifestError(
                f"tables[{index}].aggregate.measures[{measure_index}].agg '{agg}' is not "
                f"supported (expected one of {sorted(SUPPORTED_AGGREGATIONS)})"
            )
        if not isinstance(alias, str) or not _AGGREGATION_NAME_RE.match(alias):
            raise ManifestError(
                f"tables[{index}].aggregate.measures[{measure_index}].as '{alias}' is not a "
                "valid column name"
            )
        if alias in aliases:
            raise ManifestError(
                f"tables[{index}].aggregate.measures has duplicate output column '{alias}'"
            )
        aliases.add(alias)
        if entity_columns is not None and column not in entity_columns:
            raise ManifestError(
                f"tables[{index}].aggregate.measures column '{column}' is not a column of "
                f"'{table_name}'"
            )


def _validate_date_range(date_range: Any, index: int) -> None:
    if not isinstance(date_range, Mapping):
        raise ManifestError(f"tables[{index}].date_range must be an object")
    start = date_range.get("start")
    end = date_range.get("end")
    try:
        start_date = date.fromisoformat(start)
        end_date = date.fromisoformat(end)
    except (TypeError, ValueError) as exc:
        raise ManifestError(
            f"tables[{index}].date_range start/end must be ISO dates (YYYY-MM-DD)"
        ) from exc
    if start_date > end_date:
        raise ManifestError(
            f"tables[{index}].date_range start '{start}' must not be after end '{end}'"
        )


def _source_entity_columns(
    source_table: str, entity_schema: Mapping[str, Mapping[str, Any]] | None
) -> Mapping[str, Any] | None:
    if entity_schema is None:
        return None
    entity = source_table.split(".")[-1]
    return entity_schema.get(entity)


def date_dimension_rows(start_iso: str, end_iso: str) -> list[dict[str, Any]]:
    """Generate calendar dimension rows for a date range (inclusive).

    Rows are plain dicts so the logic is testable without Spark; the DLT
    notebook converts them with ``spark.createDataFrame``. ``date_key`` is the
    ``YYYYMMDD`` integer surrogate key used by the fact tables.
    """
    start = date.fromisoformat(start_iso)
    end = date.fromisoformat(end_iso)
    if start > end:
        raise ManifestError(f"date dimension start '{start_iso}' must not be after end '{end_iso}'")
    rows: list[dict[str, Any]] = []
    current = start
    while current <= end:
        rows.append(
            {
                "date_key": int(current.strftime("%Y%m%d")),
                "date": current.isoformat(),
                "year": current.year,
                "month": current.month,
                "day": current.day,
                "quarter": (current.month - 1) // 3 + 1,
                "day_of_week": current.isoweekday(),
                "day_name": current.strftime("%A"),
                "is_weekend": current.isoweekday() >= 6,
                "week_of_year": int(current.strftime("%V")),
            }
        )
        current += timedelta(days=1)
    return rows


def table_specs(manifest: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Return the Gold table specs, validated and deep-copied."""
    validate_gold_manifest(manifest)
    return [copy.deepcopy(table) for table in manifest.get("tables", [])]


def resolve_source_table(
    spec: Mapping[str, Any], variables: Mapping[str, str] | None = None
) -> str:
    """Resolve a spec's Silver source table to a fully-qualified name."""
    return resolve_path(spec["source"]["table"], variables)


def _require(value: Any, message: str) -> Any:
    if value is None:
        raise ManifestError(message)
    return value


def _check_tokens(text: str, *, context: str) -> None:
    for match in _PLACEHOLDER_RE.finditer(text):
        if match.group(1) not in _KNOWN_PLACEHOLDERS:
            raise ManifestError(
                f"{context} references unknown placeholder '{{{match.group(1)}}}' "
                f"(known: {sorted(_KNOWN_PLACEHOLDERS)})"
            )
